repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
  - repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks:
      - id: standard
  - repo: local
    hooks:
      - id: configure
        name: Configure the application
        entry: npm run configure
        language: system
        pass_filenames: false
      - id: generate-parser
        name: Generate the parser
        entry: npm run parser
        language: system
        pass_filenames: false
