repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-symlinks
  - repo: https://github.com/standard/standard
    rev: v17.1.0
    hooks:
      - id: standard
